In [46]:
import pandas as pd

In [47]:
df0 = pd.read_pickle("routerbench_0shot.pkl")

In [48]:
df0.head()

,sample_id,prompt,eval_name,WizardLM/WizardLM-13B-V1.2,claude-instant-v1,claude-v1,claude-v2,gpt-3.5-turbo-1106,gpt-4-1106-preview,meta/code-llama-instruct-34b-chat,...,claude-v1|total_cost,claude-v2|total_cost,gpt-4-1106-preview|total_cost,meta/llama-2-70b-chat|total_cost,mistralai/mixtral-8x7b-chat|total_cost,zero-one-ai/Yi-34B-Chat|total_cost,WizardLM/WizardLM-13B-V1.2|total_cost,meta/code-llama-instruct-34b-chat|total_cost,mistralai/mistral-7b-chat|total_cost,oracle_model_to_route_to
0,Chinese_character_riddles.dev.0,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.004904,0.006488,0.00973,0.000266,0.000166,0.000250,0.000103,0.000236,0.000062,no_model_correct
1,Chinese_character_riddles.dev.1,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.003096,0.004704,0.01077,0.000257,0.000227,0.000226,0.000073,0.000128,0.000050,no_model_correct
2,Chinese_character_riddles.dev.10,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.002480,0.003728,0.01105,0.000232,0.000215,0.000215,0.000138,0.000150,0.000051,zero-one-ai/Yi-34B-Chat
3,Chinese_character_riddles.dev.11,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.003088,0.004960,0.00908,0.000287,0.000117,0.000318,0.000104,0.000315,0.000045,zero-one-ai/Yi-34B-Chat
4,Chinese_character_riddles.dev.12,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.002272,0.004912,0.01322,0.000254,0.000097,0.000210,0.000112,0.000190,0.000039,no_model_correct

In [49]:
df0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36497 entries, 0 to 36496
Data columns (total 37 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   sample_id                                         36497 non-null  object
 1   prompt                                            36497 non-null  object
 2   eval_name                                         36497 non-null  object
 3   WizardLM/WizardLM-13B-V1.2                        36497 non-null  object
 4   claude-instant-v1                                 36497 non-null  object
 5   claude-v1                                         36497 non-null  object
 6   claude-v2                                         36497 non-null  object
 7   gpt-3.5-turbo-1106                                36497 non-null  object
 8   gpt-4-1106-preview                                36497 non-null  object
 9   meta/code-llama-instruct-34b-chat                 36497 non-null  object
 10  meta/llama-2-70b-chat                             36497 non-null  object
 11  mistralai/mistral-7b-chat                         36497 non-null  object
 12  mistralai/mixtral-8x7b-chat                       36497 non-null  object
 13  zero-one-ai/Yi-34B-Chat                           36497 non-null  object
 14  gpt-3.5-turbo-1106|model_response                 36497 non-null  object
 15  claude-instant-v1|model_response                  36497 non-null  object
 16  claude-v1|model_response                          36497 non-null  object
 17  claude-v2|model_response                          36497 non-null  object
 18  gpt-4-1106-preview|model_response                 36497 non-null  object
 19  meta/llama-2-70b-chat|model_response              36497 non-null  object
 20  mistralai/mixtral-8x7b-chat|model_response        36497 non-null  object
 21  zero-one-ai/Yi-34B-Chat|model_response            36497 non-null  object
 22  WizardLM/WizardLM-13B-V1.2|model_response         36497 non-null  object
 23  meta/code-llama-instruct-34b-chat|model_response  36497 non-null  object
 24  mistralai/mistral-7b-chat|model_response          36497 non-null  object
 25  gpt-3.5-turbo-1106|total_cost                     36497 non-null  float64
 26  claude-instant-v1|total_cost                      36497 non-null  float64
 27  claude-v1|total_cost                              36497 non-null  float64
 28  claude-v2|total_cost                              36497 non-null  float64
 29  gpt-4-1106-preview|total_cost                     36497 non-null  float64
 30  meta/llama-2-70b-chat|total_cost                  36497 non-null  float64
 31  mistralai/mixtral-8x7b-chat|total_cost            36497 non-null  float64
 32  zero-one-ai/Yi-34B-Chat|total_cost                36497 non-null  float64
 33  WizardLM/WizardLM-13B-V1.2|total_cost             36497 non-null  float64
 34  meta/code-llama-instruct-34b-chat|total_cost      36497 non-null  float64
 35  mistralai/mistral-7b-chat|total_cost              36497 non-null  float64
 36  oracle_model_to_route_to                          36497 non-null  object
dtypes: float64(11), object(26)
memory usage: 10.3+ MB

In [50]:
df0.shape

(36497, 37)

In [51]:
df5 = pd.read_pickle("routerbench_5shot.pkl")

In [52]:
df5.head()

,sample_id,prompt,eval_name,WizardLM/WizardLM-13B-V1.2,claude-instant-v1,claude-v1,claude-v2,gpt-3.5-turbo-1106,gpt-4-1106-preview,meta/code-llama-instruct-34b-chat,...,claude-v1|total_cost,claude-v2|total_cost,gpt-4-1106-preview|total_cost,meta/llama-2-70b-chat|total_cost,mistralai/mixtral-8x7b-chat|total_cost,zero-one-ai/Yi-34B-Chat|total_cost,WizardLM/WizardLM-13B-V1.2|total_cost,meta/code-llama-instruct-34b-chat|total_cost,mistralai/mistral-7b-chat|total_cost,oracle_model_to_route_to
0,Chinese_character_riddles.dev.0,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.004904,0.006488,0.00973,0.000266,0.000166,0.000250,0.000103,0.000236,0.000062,no_model_correct
1,Chinese_character_riddles.dev.1,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.003096,0.004704,0.01077,0.000257,0.000227,0.000226,0.000073,0.000128,0.000050,no_model_correct
2,Chinese_character_riddles.dev.10,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.002480,0.003728,0.01105,0.000232,0.000215,0.000215,0.000138,0.000150,0.000051,zero-one-ai/Yi-34B-Chat
3,Chinese_character_riddles.dev.11,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.003088,0.004960,0.00908,0.000287,0.000117,0.000318,0.000104,0.000315,0.000045,zero-one-ai/Yi-34B-Chat
4,Chinese_character_riddles.dev.12,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.002272,0.004912,0.01322,0.000254,0.000097,0.000210,0.000112,0.000190,0.000039,no_model_correct

In [53]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36511 entries, 0 to 36510
Data columns (total 37 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   sample_id                                         36511 non-null  object
 1   prompt                                            36511 non-null  object
 2   eval_name                                         36511 non-null  object
 3   WizardLM/WizardLM-13B-V1.2                        36497 non-null  object
 4   claude-instant-v1                                 36497 non-null  object
 5   claude-v1                                         36497 non-null  object
 6   claude-v2                                         36497 non-null  object
 7   gpt-3.5-turbo-1106                                36497 non-null  object
 8   gpt-4-1106-preview                                36497 non-null  object
 9   meta/code-llama-instruct-34b-chat                 36497 non-null  object
 10  meta/llama-2-70b-chat                             36497 non-null  object
 11  mistralai/mistral-7b-chat                         36497 non-null  object
 12  mistralai/mixtral-8x7b-chat                       36497 non-null  object
 13  zero-one-ai/Yi-34B-Chat                           36497 non-null  object
 14  gpt-3.5-turbo-1106|model_response                 36511 non-null  object
 15  claude-instant-v1|model_response                  36511 non-null  object
 16  claude-v1|model_response                          36511 non-null  object
 17  claude-v2|model_response                          36511 non-null  object
 18  gpt-4-1106-preview|model_response                 36511 non-null  object
 19  meta/llama-2-70b-chat|model_response              36511 non-null  object
 20  mistralai/mixtral-8x7b-chat|model_response        36511 non-null  object
 21  zero-one-ai/Yi-34B-Chat|model_response            36511 non-null  object
 22  WizardLM/WizardLM-13B-V1.2|model_response         36511 non-null  object
 23  meta/code-llama-instruct-34b-chat|model_response  36511 non-null  object
 24  mistralai/mistral-7b-chat|model_response          36511 non-null  object
 25  gpt-3.5-turbo-1106|total_cost                     36511 non-null  float64
 26  claude-instant-v1|total_cost                      36511 non-null  float64
 27  claude-v1|total_cost                              36511 non-null  float64
 28  claude-v2|total_cost                              36511 non-null  float64
 29  gpt-4-1106-preview|total_cost                     36511 non-null  float64
 30  meta/llama-2-70b-chat|total_cost                  36511 non-null  float64
 31  mistralai/mixtral-8x7b-chat|total_cost            36511 non-null  float64
 32  zero-one-ai/Yi-34B-Chat|total_cost                36511 non-null  float64
 33  WizardLM/WizardLM-13B-V1.2|total_cost             36511 non-null  float64
 34  meta/code-llama-instruct-34b-chat|total_cost      36511 non-null  float64
 35  mistralai/mistral-7b-chat|total_cost              36511 non-null  float64
 36  oracle_model_to_route_to                          36511 non-null  object
dtypes: float64(11), object(26)
memory usage: 10.3+ MB

In [54]:
df5.shape

(36511, 37)

In [55]:
# Map user-specified model names to the actual column names in df0
model_columns = [
    'sample_id',
    'prompt',
    'eval_name',
    'gpt-4-1106-preview',      # GPT-4
    'gpt-3.5-turbo-1106',     # GPT-3.5
    'claude-v1',              # Claude v1
    'claude-v2',              # Claude v2
    'claude-instant-v1'       # Claude Instant
]

# Keep only the specified columns
df0_filtered = df0[model_columns]
display(df0_filtered.head())

,sample_id,prompt,eval_name,gpt-4-1106-preview,gpt-3.5-turbo-1106,claude-v1,claude-v2,claude-instant-v1
0,Chinese_character_riddles.dev.0,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0
1,Chinese_character_riddles.dev.1,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0
2,Chinese_character_riddles.dev.10,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0
3,Chinese_character_riddles.dev.11,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,1.0,0.0,0.0,0.0,0.0
4,Chinese_character_riddles.dev.12,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0

In [56]:
df0_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36497 entries, 0 to 36496
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sample_id           36497 non-null  object
 1   prompt              36497 non-null  object
 2   eval_name           36497 non-null  object
 3   gpt-4-1106-preview  36497 non-null  object
 4   gpt-3.5-turbo-1106  36497 non-null  object
 5   claude-v1           36497 non-null  object
 6   claude-v2           36497 non-null  object
 7   claude-instant-v1   36497 non-null  object
dtypes: object(8)
memory usage: 2.2+ MB

In [57]:
from google.colab import files

# Export to CSV
df0_filtered.to_csv('df0_filtered.csv', index=False)

# Download the file to your local system
files.download('df0_filtered.csv')

In [59]:
df0_gpt4 = df0_filtered[['gpt-4-1106-preview']]

In [60]:
print(df0_gpt4.describe())

        gpt-4-1106-preview
count              36497.0
unique                12.0
top                    1.0
freq               23446.0

In [62]:
df0_gpt4.value_counts()

gpt-4-1106-preview
1.00                  23446
0.00                   5332
0.75                   5224
0.50                   2105
0.25                    365
0.10                     10
0.90                      7
0.20                      2
0.30                      2
0.80                      2
0.70                      1
0.40                      1
Name: count, dtype: int64

In [63]:
# Map user-specified model names to the actual column names in df5
model_columns = [
    'sample_id',
    'prompt',
    'eval_name',
    'gpt-4-1106-preview',      # GPT-4
    'gpt-3.5-turbo-1106',     # GPT-3.5
    'claude-v1',              # Claude v1
    'claude-v2',              # Claude v2
    'claude-instant-v1'       # Claude Instant
]

# Keep only the specified columns
df5_filtered = df5[model_columns]
display(df5_filtered.head())

,sample_id,prompt,eval_name,gpt-4-1106-preview,gpt-3.5-turbo-1106,claude-v1,claude-v2,claude-instant-v1
0,Chinese_character_riddles.dev.0,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0
1,Chinese_character_riddles.dev.1,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0
2,Chinese_character_riddles.dev.10,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0
3,Chinese_character_riddles.dev.11,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,1.0,0.0,0.0,0.0,0.0
4,Chinese_character_riddles.dev.12,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0

In [65]:
# Export to CSV
df5_filtered.to_csv('df5_filtered.csv', index=False)

# Download the file to your local system
files.download('df5_filtered.csv')

In [67]:
dfraw = pd.read_pickle("routerbench_raw.pkl")

In [68]:
dfraw.shape

(401467, 8)

In [69]:
dfraw.head()

,index,sample_id,prompt,eval_name,performance,model_response,model_name,cost
0,0,mtbench-math.dev.0,"[""Imagine you are participating in a race with...",mtbench-math,0.1,"['If I have just overtaken the second person, ...",gpt-3.5-turbo-1106,0.000194
1,1,mtbench-math.dev.1,['You can see a beautiful red house to your le...,mtbench-math,1.0,['The White House is located in Washington D.C...,gpt-3.5-turbo-1106,0.000134
2,2,mtbench-math.dev.10,"['The vertices of a triangle are at points (0,...",mtbench-math,0.2,"['To find the area of the triangle, we can use...",gpt-3.5-turbo-1106,0.001197
3,3,mtbench-math.dev.11,"[""A tech startup invests $8000 in software dev...",mtbench-math,1.0,"['In the first year, the startup invested $800...",gpt-3.5-turbo-1106,0.000300
4,4,mtbench-math.dev.12,"[""In a survey conducted at a local high school...",mtbench-math,0.1,['To find the probability that a student would...,gpt-3.5-turbo-1106,0.000761

In [71]:
dfraw.info()

<class 'pandas.core.frame.DataFrame'>
Index: 401467 entries, 0 to 276335
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   index           401467 non-null  int64
 1   sample_id       401467 non-null  object
 2   prompt          401467 non-null  object
 3   eval_name       401467 non-null  object
 4   performance     401467 non-null  object
 5   model_response  401467 non-null  object
 6   model_name      401467 non-null  object
 7   cost            401467 non-null  float64
dtypes: float64(1), int64(1), object(6)
memory usage: 27.6+ MB