# RouterBench data

Loads RouterBench (0-shot and 5-shot), looks at the data and writes two CSVs to read:
`df0_filtered.csv` (0-shot) and `df5_filtered.csv` (5-shot), with each model's score and cost.

The experiment scripts do not use these files; they use the output of `src/data/build_dataset.py`.
Do not re-save the CSVs from Excel: it changes the separator and garbles non-English text.

In [1]:
try:
    import huggingface_hub  # noqa: F401
except ImportError:
    %pip install -q huggingface_hub

In [2]:
from pathlib import Path

import pandas as pd
from huggingface_hub import hf_hub_download

FILES = {"0shot": "routerbench_0shot.pkl", "5shot": "routerbench_5shot.pkl"}

for name in FILES.values():
    if not Path(name).exists():
        hf_hub_download(
            repo_id="withmartian/routerbench", filename=name, repo_type="dataset", local_dir="."
        )

## 1. Look at the data

In [3]:
df0 = pd.read_pickle(FILES["0shot"])
df0.head()

,sample_id,prompt,eval_name,WizardLM/WizardLM-13B-V1.2,claude-instant-v1,claude-v1,claude-v2,gpt-3.5-turbo-1106,gpt-4-1106-preview,meta/code-llama-instruct-34b-chat,...,claude-v1|total_cost,claude-v2|total_cost,gpt-4-1106-preview|total_cost,meta/llama-2-70b-chat|total_cost,mistralai/mixtral-8x7b-chat|total_cost,zero-one-ai/Yi-34B-Chat|total_cost,WizardLM/WizardLM-13B-V1.2|total_cost,meta/code-llama-instruct-34b-chat|total_cost,mistralai/mistral-7b-chat|total_cost,oracle_model_to_route_to
0,Chinese_character_riddles.dev.0,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.004904,0.006488,0.00973,0.000266,0.000166,0.000250,0.000103,0.000236,0.000062,no_model_correct
1,Chinese_character_riddles.dev.1,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.003096,0.004704,0.01077,0.000257,0.000227,0.000226,0.000073,0.000128,0.000050,no_model_correct
2,Chinese_character_riddles.dev.10,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.002480,0.003728,0.01105,0.000232,0.000215,0.000215,0.000138,0.000150,0.000051,zero-one-ai/Yi-34B-Chat
3,Chinese_character_riddles.dev.11,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.003088,0.004960,0.00908,0.000287,0.000117,0.000318,0.000104,0.000315,0.000045,zero-one-ai/Yi-34B-Chat
4,Chinese_character_riddles.dev.12,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.002272,0.004912,0.01322,0.000254,0.000097,0.000210,0.000112,0.000190,0.000039,no_model_correct

In [4]:
df0.info()

<class 'pandas.DataFrame'>
RangeIndex: 36497 entries, 0 to 36496
Data columns (total 37 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   sample_id                                         36497 non-null  object
 1   prompt                                            36497 non-null  object
 2   eval_name                                         36497 non-null  object
 3   WizardLM/WizardLM-13B-V1.2                        36497 non-null  object
 4   claude-instant-v1                                 36497 non-null  object
 5   claude-v1                                         36497 non-null  object
 6   claude-v2                                         36497 non-null  object
 7   gpt-3.5-turbo-1106                                36497 non-null  object
 8   gpt-4-1106-preview                                36497 non-null  object
 9   meta/code-llama-instruct-34b-chat                 36497 non-null  object
 10  meta/llama-2-70b-chat                             36497 non-null  object
 11  mistralai/mistral-7b-chat                         36497 non-null  object
 12  mistralai/mixtral-8x7b-chat                       36497 non-null  object
 13  zero-one-ai/Yi-34B-Chat                           36497 non-null  object
 14  gpt-3.5-turbo-1106|model_response                 36497 non-null  object
 15  claude-instant-v1|model_response                  36497 non-null  object
 16  claude-v1|model_response                          36497 non-null  object
 17  claude-v2|model_response                          36497 non-null  object
 18  gpt-4-1106-preview|model_response                 36497 non-null  object
 19  meta/llama-2-70b-chat|model_response              36497 non-null  object
 20  mistralai/mixtral-8x7b-chat|model_response        36497 non-null  object
 21  zero-one-ai/Yi-34B-Chat|model_response            36497 non-null  object
 22  WizardLM/WizardLM-13B-V1.2|model_response         36497 non-null  object
 23  meta/code-llama-instruct-34b-chat|model_response  36497 non-null  object
 24  mistralai/mistral-7b-chat|model_response          36497 non-null  object
 25  gpt-3.5-turbo-1106|total_cost                     36497 non-null  float64
 26  claude-instant-v1|total_cost                      36497 non-null  float64
 27  claude-v1|total_cost                              36497 non-null  float64
 28  claude-v2|total_cost                              36497 non-null  float64
 29  gpt-4-1106-preview|total_cost                     36497 non-null  float64
 30  meta/llama-2-70b-chat|total_cost                  36497 non-null  float64
 31  mistralai/mixtral-8x7b-chat|total_cost            36497 non-null  float64
 32  zero-one-ai/Yi-34B-Chat|total_cost                36497 non-null  float64
 33  WizardLM/WizardLM-13B-V1.2|total_cost             36497 non-null  float64
 34  meta/code-llama-instruct-34b-chat|total_cost      36497 non-null  float64
 35  mistralai/mistral-7b-chat|total_cost              36497 non-null  float64
 36  oracle_model_to_route_to                          36497 non-null  object
dtypes: float64(11), object(26)
memory usage: 10.3+ MB

In [5]:
df5 = pd.read_pickle(FILES["5shot"])
df5.head()

,sample_id,prompt,eval_name,WizardLM/WizardLM-13B-V1.2,claude-instant-v1,claude-v1,claude-v2,gpt-3.5-turbo-1106,gpt-4-1106-preview,meta/code-llama-instruct-34b-chat,...,claude-v1|total_cost,claude-v2|total_cost,gpt-4-1106-preview|total_cost,meta/llama-2-70b-chat|total_cost,mistralai/mixtral-8x7b-chat|total_cost,zero-one-ai/Yi-34B-Chat|total_cost,WizardLM/WizardLM-13B-V1.2|total_cost,meta/code-llama-instruct-34b-chat|total_cost,mistralai/mistral-7b-chat|total_cost,oracle_model_to_route_to
0,Chinese_character_riddles.dev.0,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.004904,0.006488,0.00973,0.000266,0.000166,0.000250,0.000103,0.000236,0.000062,no_model_correct
1,Chinese_character_riddles.dev.1,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.003096,0.004704,0.01077,0.000257,0.000227,0.000226,0.000073,0.000128,0.000050,no_model_correct
2,Chinese_character_riddles.dev.10,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.002480,0.003728,0.01105,0.000232,0.000215,0.000215,0.000138,0.000150,0.000051,zero-one-ai/Yi-34B-Chat
3,Chinese_character_riddles.dev.11,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.003088,0.004960,0.00908,0.000287,0.000117,0.000318,0.000104,0.000315,0.000045,zero-one-ai/Yi-34B-Chat
4,Chinese_character_riddles.dev.12,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.002272,0.004912,0.01322,0.000254,0.000097,0.000210,0.000112,0.000190,0.000039,no_model_correct

In [6]:
df5.info()

<class 'pandas.DataFrame'>
RangeIndex: 36511 entries, 0 to 36510
Data columns (total 37 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   sample_id                                         36511 non-null  object
 1   prompt                                            36511 non-null  object
 2   eval_name                                         36511 non-null  object
 3   WizardLM/WizardLM-13B-V1.2                        36497 non-null  object
 4   claude-instant-v1                                 36497 non-null  object
 5   claude-v1                                         36497 non-null  object
 6   claude-v2                                         36497 non-null  object
 7   gpt-3.5-turbo-1106                                36497 non-null  object
 8   gpt-4-1106-preview                                36497 non-null  object
 9   meta/code-llama-instruct-34b-chat                 36497 non-null  object
 10  meta/llama-2-70b-chat                             36497 non-null  object
 11  mistralai/mistral-7b-chat                         36497 non-null  object
 12  mistralai/mixtral-8x7b-chat                       36497 non-null  object
 13  zero-one-ai/Yi-34B-Chat                           36497 non-null  object
 14  gpt-3.5-turbo-1106|model_response                 36511 non-null  object
 15  claude-instant-v1|model_response                  36511 non-null  object
 16  claude-v1|model_response                          36511 non-null  object
 17  claude-v2|model_response                          36511 non-null  object
 18  gpt-4-1106-preview|model_response                 36511 non-null  object
 19  meta/llama-2-70b-chat|model_response              36511 non-null  object
 20  mistralai/mixtral-8x7b-chat|model_response        36511 non-null  object
 21  zero-one-ai/Yi-34B-Chat|model_response            36511 non-null  object
 22  WizardLM/WizardLM-13B-V1.2|model_response         36511 non-null  object
 23  meta/code-llama-instruct-34b-chat|model_response  36511 non-null  object
 24  mistralai/mistral-7b-chat|model_response          36511 non-null  object
 25  gpt-3.5-turbo-1106|total_cost                     36511 non-null  float64
 26  claude-instant-v1|total_cost                      36511 non-null  float64
 27  claude-v1|total_cost                              36511 non-null  float64
 28  claude-v2|total_cost                              36511 non-null  float64
 29  gpt-4-1106-preview|total_cost                     36511 non-null  float64
 30  meta/llama-2-70b-chat|total_cost                  36511 non-null  float64
 31  mistralai/mixtral-8x7b-chat|total_cost            36511 non-null  float64
 32  zero-one-ai/Yi-34B-Chat|total_cost                36511 non-null  float64
 33  WizardLM/WizardLM-13B-V1.2|total_cost             36511 non-null  float64
 34  meta/code-llama-instruct-34b-chat|total_cost      36511 non-null  float64
 35  mistralai/mistral-7b-chat|total_cost              36511 non-null  float64
 36  oracle_model_to_route_to                          36511 non-null  object
dtypes: float64(11), object(26)
memory usage: 10.3+ MB

## 2. Models

RouterBench column keys of the models in this study. Delete a line to leave a model out.

In [7]:
MODELS = {
    "gpt-4-1106-preview": "GPT-4",
    "gpt-3.5-turbo-1106": "GPT-3.5",
    "claude-v1": "Claude v1",
    "claude-v2": "Claude v2",
    "claude-instant-v1": "Claude Instant",
}
MODEL_KEYS = list(MODELS)

## 3. Problems the cleaning has to handle

In [8]:
def problems(df):
    scores = df[MODEL_KEYS].apply(pd.to_numeric, errors="coerce")
    return pd.Series(
        {
            "rows": len(df),
            "unique sample_ids": df["sample_id"].nunique(),
            "rows with a missing score": int(scores.isna().any(axis=1).sum()),
            "extra rows of a repeated sample_id": int(df["sample_id"].duplicated().sum()),
            "extra rows of a repeated prompt": int(df["prompt"].astype(str).duplicated().sum()),
        }
    )


pd.DataFrame({"0-shot": problems(df0), "5-shot": problems(df5)})

                                    0-shot  5-shot
rows                                 36497   36511
unique sample_ids                    36497   36497
rows with a missing score                0      28
extra rows of a repeated sample_id       0      14
extra rows of a repeated prompt         16      14

In [9]:
# Rows that share a sample_id, with each copy's prompt length.
repeated = df5[df5["sample_id"].duplicated(keep=False)].sort_values("sample_id")
repeated = repeated.assign(prompt_chars=repeated["prompt"].astype(str).str.len())
repeated[["sample_id", "prompt_chars"] + MODEL_KEYS].head(10)

,sample_id,prompt_chars,gpt-4-1106-preview,gpt-3.5-turbo-1106,claude-v1,claude-v2,claude-instant-v1
1598,arc-challenge.val.136,3884,NaN,1.0,NaN,NaN,NaN
1599,arc-challenge.val.136,1942,1.0,NaN,1.0,1.0,1.0
1600,arc-challenge.val.137,3806,NaN,0.0,NaN,NaN,NaN
1601,arc-challenge.val.137,1903,1.0,NaN,0.0,0.0,0.0
1640,arc-challenge.val.172,3920,NaN,1.0,NaN,NaN,NaN
1641,arc-challenge.val.172,1960,1.0,NaN,1.0,1.0,1.0
1643,arc-challenge.val.174,3928,NaN,1.0,NaN,NaN,NaN
1644,arc-challenge.val.174,1964,1.0,NaN,1.0,0.0,1.0
1661,arc-challenge.val.19,4284,NaN,1.0,NaN,NaN,NaN
1662,arc-challenge.val.19,2142,1.0,NaN,1.0,0.0,1.0

In the 5-shot file, 14 ARC questions appear twice. GPT-3.5 was scored on a prompt about twice
the normal length, the other four models on the normal prompt. No single prompt has all five
scores, so the cleaning below drops both rows. The 0-shot file has these questions complete.

## 4. Clean and export

Keep each model's score and cost, drop rows with a missing value, keep one row per question.

In [10]:
COLUMNS = ["sample_id", "prompt", "eval_name"] + MODEL_KEYS + [f"{key}|total_cost" for key in MODEL_KEYS]


def clean(df):
    out = df[COLUMNS].copy()
    out[MODEL_KEYS] = out[MODEL_KEYS].apply(pd.to_numeric, errors="coerce")
    out = out.dropna()  # rows with a missing score or cost
    out = out.drop_duplicates(subset="sample_id")  # one row per question
    return out.reset_index(drop=True)


df0_filtered = clean(df0)
df5_filtered = clean(df5)
print(f"0-shot: {len(df0)} -> {len(df0_filtered)} rows")
print(f"5-shot: {len(df5)} -> {len(df5_filtered)} rows")

df0_filtered.to_csv("df0_filtered.csv", index=False)
df5_filtered.to_csv("df5_filtered.csv", index=False)

0-shot: 36497 -> 36497 rows
5-shot: 36511 -> 36483 rows

## 5. Download the files (Colab)

In [11]:
try:
    from google.colab import files
except ImportError:
    print("Not running in Colab; the CSVs are in the notebook's folder.")
else:
    files.download("df0_filtered.csv")
    files.download("df5_filtered.csv")

Not running in Colab; the CSVs are in the notebook's folder.